### PR TITLE
adding swagger and swagger-ui.

### PR DESCRIPTION
**Pull request by munk**
Swagger to allow exploration of the API #112
Everything in resources/api-browser is just from swagger, so it's not very interesting. 

StaticResourceConfiguration.java is supposed to allow access to the docs at /api-browser, but I'm seeing a 404 when I test it. Any thoughts?

### CODE REVIEW

**Comment by munk** [comment]
Closing and reopening to retry the build as it failed because of a timeout

**Comment by benjamin-heasly** [comment]
Hi @munk.  Sorry I'm late to the party.  I was on vacation, then busy.

I think this could be cool.

Anything new on the 404?  I don't have any experience configuring swagger myself.

**Comment by munk** [comment]
I think the problem is that Tomcat doesn't know where the static assets are. Swagger produces static assets at build time, which should then be served by the app container. I _think_ that the assets are there, and tomcat isn't configured correctly to serve them. I'll verify that as soon as possible.

**Comment by munk** [comment]
@benjamin-heasly It turns out the 404 was just because I hadn't run the build correctly. I assumed gradle bootRun would do that for me. This is working now and you can access the swagger ui at /api-browser/index.html once it's merged.

**Comment by benjamin-heasly** [comment]
Cool.  I think this is working.  Here's what worked for me:
- `git checkout -b munk-add-swagger master`
- `git pull https://github.com/munk/openhds-rest.git add-swagger`
- `gradle clean stage`
- `java -Dfile.encoding=UTF-8 -jar build/libs/openhds-rest-0.0.1-SNAPSHOT.jar --sampleDataSize=2`

I noticed that it took much longer for the server to start -- about 300 seconds where it used to take about 30 seconds.  This would interfere with the Heroku deployment, which expects startup in <60 seconds.  Do you think there's a way to speed this up?

I'm able to see XML and JSON at paths like `http://localhost:8080/api-docs/default/social-group-rest-controller`.

But I don't know how to see the nice browser UI.  I get a 404 at `http://localhost:8080/api-browser/index.html`  Is that the correct path?

**Comment by munk** [comment]
/api-browser/index.html should be the right url. I may not have it in the right location in src, so it's not building properly. I'll look into that tonight.

There's also a small problem with dates, where it uses reflection to get their structure, rather than casting it as a string. I think that's just some configuration we need to add.

I don't know how to improve the build time, but we could leave this on a branch for developers to use to explore locally.

**Pull request closed without merging**
